use super::*;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
pub struct ExecutionBudget {
    pub token_cap: Option<u64>,
    pub byte_cap: Option<usize>,
    pub runtime_ms_cap: Option<u64>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default)]
pub struct BudgetUsage {
    pub tokens: u64,
    pub bytes: usize,
    pub runtime_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct KernelPacket {
    pub packet_id: Option<String>,
    pub format: String,
    pub body: Value,
    pub token_usage: Option<u64>,
    pub runtime_ms: Option<u64>,
    pub metadata: Value,
}

impl Default for KernelPacket {
    fn default() -> Self {
        Self {
            packet_id: None,
            format: default_packet_format(),
            body: Value::Null,
            token_usage: None,
            runtime_ms: None,
            metadata: Value::Null,
        }
    }
}

impl KernelPacket {
    pub fn from_value(value: Value, fallback_packet_id: Option<String>) -> Self {
        let packet_id = value
            .get("packet_id")
            .and_then(Value::as_str)
            .map(ToOwned::to_owned)
            .or(fallback_packet_id);

        Self {
            packet_id,
            format: default_packet_format(),
            body: value,
            token_usage: None,
            runtime_ms: None,
            metadata: Value::Null,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct KernelRequest {
    pub target: String,
    pub input_packets: Vec<KernelPacket>,
    pub budget: ExecutionBudget,
    pub policy_context: Value,
    pub reducer_input: Value,
}

impl Default for KernelRequest {
    fn default() -> Self {
        Self {
            target: String::new(),
            input_packets: Vec::new(),
            budget: ExecutionBudget::default(),
            policy_context: Value::Null,
            reducer_input: Value::Null,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct KernelStepRequest {
    pub id: String,
    pub target: String,
    pub depends_on: Vec<String>,
    pub input_packets: Vec<KernelPacket>,
    pub policy_context: Value,
    pub reducer_input: Value,
    pub budget: ExecutionBudget,
    pub reactive: Option<KernelStepReactiveConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct KernelSequenceRequest {
    pub budget: ExecutionBudget,
    pub steps: Vec<KernelStepRequest>,
    pub reactive: ReactiveSequenceConfig,
}

fn autogenerated_sequence_step_id(target: &str, index: usize) -> String {
    format!("{}-{index}", target.replace('.', "-"))
}

pub fn normalize_sequence_request(
    mut req: KernelSequenceRequest,
) -> Result<KernelSequenceRequest, KernelError> {
    let mut ids = BTreeSet::new();
    for (index, step) in req.steps.iter_mut().enumerate() {
        if step.target.trim().is_empty() {
            return Err(KernelError::InvalidRequest {
                detail: format!("sequence step {index} target cannot be empty"),
            });
        }

        let trimmed_id = step.id.trim();
        step.id = if trimmed_id.is_empty() {
            autogenerated_sequence_step_id(&step.target, index)
        } else {
            trimmed_id.to_string()
        };

        if !ids.insert(step.id.clone()) {
            return Err(KernelError::InvalidRequest {
                detail: format!("sequence step id '{}' must be unique", step.id),
            });
        }
    }

    for step in &req.steps {
        for dep in &step.depends_on {
            if dep.trim().is_empty() {
                return Err(KernelError::InvalidRequest {
                    detail: format!("sequence step '{}' has an empty dependency id", step.id),
                });
            }
            if dep == &step.id {
                return Err(KernelError::InvalidRequest {
                    detail: format!("sequence step '{}' cannot depend on itself", step.id),
                });
            }
            if !ids.contains(dep) {
                return Err(KernelError::InvalidRequest {
                    detail: format!(
                        "sequence step '{}' depends on unknown step '{}'",
                        step.id, dep
                    ),
                });
            }
        }
    }

    Ok(req)
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(default)]
pub struct ReactiveSequenceConfig {
    pub enabled: bool,
    pub task_id: Option<String>,
    pub append_focused_map: bool,
    pub mode: ReactiveReplanMode,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ReactiveReplanMode {
    #[default]
    Basic,
    TaskAware,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(default)]
pub struct KernelStepReactiveConfig {
    pub event_kinds: Vec<suite_packet_core::AgentStateEventKind>,
    pub path_globs: Vec<String>,
    pub rerun_on_focus_change: bool,
    pub skip_if_inputs_unchanged: bool,
    pub produces_focus: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KernelStepResponse {
    pub id: String,
    pub target: String,
    pub status: String,
    pub response: Option<KernelResponse>,
    pub failure: Option<KernelFailure>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KernelSequenceResponse {
    pub request_id: u64,
    pub scheduled: Vec<String>,
    pub skipped: Vec<String>,
    pub budget_exhausted: bool,
    pub step_results: Vec<KernelStepResponse>,
    pub metadata: Value,
}

pub trait SequenceObserver {
    fn on_step_started(&mut self, _position: usize, _step: &KernelStepRequest) {}

    fn on_step_completed(
        &mut self,
        _position: usize,
        _step: &KernelStepRequest,
        _response: &KernelResponse,
    ) {
    }

    fn on_step_failed(
        &mut self,
        _position: usize,
        _step: &KernelStepRequest,
        _failure: &KernelFailure,
    ) {
    }

    fn on_replan_applied(
        &mut self,
        _after_step: Option<&str>,
        _event_count: usize,
        _applied_mutations: &Value,
    ) {
    }
}

#[derive(Default)]
pub struct NoopSequenceObserver;

impl SequenceObserver for NoopSequenceObserver {}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KernelResponse {
    pub request_id: u64,
    pub target: String,
    pub output_packets: Vec<KernelPacket>,
    pub audit: KernelAudit,
    pub metadata: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KernelAudit {
    pub reducer: String,
    pub input_packets: usize,
    pub output_packets: usize,
    pub budget: ExecutionBudget,
    pub input_usage: BudgetUsage,
    pub output_usage: BudgetUsage,
    pub total_usage: BudgetUsage,
    #[serde(default)]
    pub governance: GovernanceAudit,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct GovernanceAudit {
    pub enabled: bool,
    pub config_path: Option<String>,
    pub reducer_execution: Option<ReducerExecutionAudit>,
    pub input_audits: Vec<guardy_core::AuditResult>,
    pub output_audits: Vec<guardy_core::AuditResult>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct ReducerExecutionAudit {
    pub reducer: String,
    pub allowed: bool,
    pub matched_by: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct ReducerResult {
    pub output_packets: Vec<KernelPacket>,
    pub metadata: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KernelFailure {
    pub code: String,
    pub message: String,
    pub target: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BudgetStage {
    Input,
    Total,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BudgetMetric {
    Tokens,
    Bytes,
    RuntimeMs,
}

#[derive(Debug, Error)]
pub enum KernelError {
    #[error("kernel target cannot be empty")]
    EmptyTarget,

    #[error("unknown kernel target '{target}'")]
    UnknownTarget {
        target: String,
        registered: Vec<String>,
    },

    #[error("invalid request: {detail}")]
    InvalidRequest { detail: String },

    #[error("budget exceeded for {metric:?} at {stage:?}: used {used} > cap {cap}")]
    BudgetExceeded {
        target: String,
        stage: BudgetStage,
        metric: BudgetMetric,
        used: u64,
        cap: u64,
    },

    #[error("failed to read packet file '{path}': {detail}")]
    PacketRead { path: String, detail: String },

    #[error("failed to parse packet JSON from '{path}': {detail}")]
    PacketParse { path: String, detail: String },

    #[error("reducer '{target}' failed: {detail}")]
    ReducerFailed { target: String, detail: String },

    #[error("scheduler error: {detail}")]
    SchedulerFailed { detail: String },

    #[error("cache lock failed: {detail}")]
    CacheLock { detail: String },

    #[error("policy violation for target '{target}': {detail}")]
    PolicyViolation { target: String, detail: String },
}

impl KernelError {
    pub fn structured(&self) -> KernelFailure {
        match self {
            KernelError::EmptyTarget => KernelFailure {
                code: "empty_target".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::UnknownTarget { target, .. } => KernelFailure {
                code: "unknown_target".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
            KernelError::InvalidRequest { .. } => KernelFailure {
                code: "invalid_request".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::BudgetExceeded { target, .. } => KernelFailure {
                code: "budget_exceeded".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
            KernelError::PacketRead { .. } => KernelFailure {
                code: "packet_read_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::PacketParse { .. } => KernelFailure {
                code: "packet_parse_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::ReducerFailed { target, .. } => KernelFailure {
                code: "reducer_failed".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
            KernelError::SchedulerFailed { .. } => KernelFailure {
                code: "scheduler_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::CacheLock { .. } => KernelFailure {
                code: "cache_lock_failed".to_string(),
                message: self.to_string(),
                target: None,
            },
            KernelError::PolicyViolation { target, .. } => KernelFailure {
                code: "policy_violation".to_string(),
                message: self.to_string(),
                target: Some(target.clone()),
            },
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct PolicyGuard {
    pub(crate) config: guardy_core::ContextConfig,
    pub(crate) config_path: String,
    pub(crate) policy_hash: String,
}
