#![recursion_limit = "256"]

pub mod agent_surface;
pub mod broker_client;
mod cli_defs;
mod cli_runtime;
pub mod cmd_agent_prompt;
pub mod cmd_build;
pub mod cmd_compact;
pub mod cmd_common;
pub mod cmd_common_machine;
mod cmd_common_machine_support;
pub mod cmd_common_runtime;
pub mod cmd_context;
pub mod cmd_context_kernel;
pub mod cmd_context_recall;
pub mod cmd_context_state;
pub mod cmd_context_store;
pub mod cmd_cover;
pub mod cmd_daemon;
pub mod cmd_daemon_client;
pub mod cmd_daemon_commands;
pub mod cmd_diff;
pub mod cmd_doctor;
pub mod cmd_guard;
pub mod cmd_hook;
pub mod cmd_impact;
pub mod cmd_map;
pub mod cmd_map_repo;
pub mod cmd_mcp;
pub mod cmd_packet;
pub mod cmd_proxy;
pub mod cmd_setup;
pub mod cmd_shard;
pub mod cmd_stack;
pub mod packet28_agent;
pub mod route_registry;
pub mod task_runtime;

pub use cli_defs::*;
pub use cli_runtime::*;
