[package]
name = "mapy-core"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[features]
default = []
shared-repository-scan = []

[dependencies]
blake3.workspace = true
fs2 = "0.4"
suite-packet-core.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
ignore.workspace = true
packet28-binary-codec.workspace = true
packet28-state-fs.workspace = true
tree-sitter = "0.26"
tree-sitter-java = "0.23"
tree-sitter-rust = "0.24"
tree-sitter-python = "0.23"
tree-sitter-typescript = "0.23"
tree-sitter-javascript = "0.25"
tree-sitter-go = "0.23"
tree-sitter-cpp = "0.23"

[dev-dependencies]
packet28-search-core.workspace = true
tempfile.workspace = true
