[package]
name = "suite-cli"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[[bin]]
name = "Packet28"
path = "src/main.rs"

[dependencies]
testy-cli-common.workspace = true
diffy-core.workspace = true
testy-core.workspace = true
guardy-core.workspace = true
contextq-core.workspace = true
context-kernel-core.workspace = true
context-memory-core.workspace = true
stacky-core.workspace = true
buildy-core.workspace = true
mapy-core.workspace = true
suite-proxy-core.workspace = true
suite-ingest.workspace = true
suite-foundation-core.workspace = true
suite-packet-core.workspace = true
packet28-daemon-client.workspace = true
packet28-daemon-core.workspace = true
packet28-daemon-protocol.workspace = true
packet28-reducer-core.workspace = true
clap.workspace = true
anyhow.workspace = true
colored.workspace = true
serde.workspace = true
serde_json.workspace = true
yaml_serde.workspace = true
toml.workspace = true
libc.workspace = true
blake3.workspace = true
shell-words.workspace = true
glob.workspace = true
sha2.workspace = true
hex.workspace = true
signal-hook = "0.4.4"
rusqlite.workspace = true
regex.workspace = true
tokio.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[build-dependencies]
toml.workspace = true
